
language: julia

os:
  - linux
  - osx

julia:
  - 1.4
  - 1.5
  - 1.6
  - nightly

notifications:
  email: false

#matrix:
#  allow_failures:
#    - julia: nightly

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("Multitaper"; coverage=true)'

after_success:
  # Install required packages for coverage and documentation
  - julia --project -e 'import Pkg; Pkg.add("Coverage");'

  # Submit test coverage report
  - julia --project -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
