
# Lifted very closely and with a great deal of gratitude from: 
#
#   https://bitbucket.org/mortenpi/documenterexample.jl/src/master/docs/make.jl
#

image: julia:latest

pipelines:
  default:
    - step:
        name: tests
        script:
            - export JULIA_PROJECT=@.
            - julia -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
            - julia test/runtests.jl
    - step:
        name: documentation
        script:
            - apt-get update && apt-get install -y git
            - export JULIA_PROJECT=@.
            - julia -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
            - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
            - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
            - julia --project=docs/ docs/make.jl

